version: "3"
services:
  my-app:
    container_name: usr_mgt_ui
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - usr-mgt-net
    volumes:
      - '.:/app'
      - '/app/node_modules'
